export {default as Header} from "./Header"
export {default as FirstScreen} from "./FirstScreen"
export {default as SecondScreen} from "./SecondScreen"
export {default as ThirdScreen} from "./ThirdScreen"
export {default as FourthScreen} from "./FourthScreen"
export {default as FifthScreen} from "./FifthScreen"
export {default as SixthScreen} from "./SixthScreen"